Repository zskteam-20200911-130000/zsksample_rails01, pull requests merged in 2020-09, with the labels that each got.

#20 feat: Userモデルのnameとemailに存在性のバリデーションを追加
  app/models/user.rb
Labels: feature

#21 test: Userのモデルスペックへvalidationのテストを追加
  spec/models/user_spec.rb
Labels: test

#22 test: Userのリクエストスペックを追加
  spec/requests/users_spec.rb
Labels: test

#24 Feature/associate user with microposts
  app/models/micropost.rb
  app/models/user.rb
Labels: feature

#25 Feat/add validation to content of microposts
  app/models/micropost.rb
Labels: feature

#31 Micropostモデルのテスト追加
  spec/models/micropost_spec.rb
Labels: test

#30 feat:Micropostに基本的な処理を追加
  app/controllers/microposts_controller.rb
Labels: feature

#33 Merge develop to master
  app/assets/stylesheets/microposts.scss
  app/controllers/microposts_controller.rb
  app/helpers/microposts_helper.rb
  app/models/micropost.rb
  app/models/user.rb
  app/views/microposts/edit.html.erb
  app/views/microposts/index.html.erb
  app/views/microposts/new.html.erb
  app/views/microposts/show.html.erb
  config/routes.rb
  db/migrate/20200916073038_create_microposts.rb
  db/schema.rb
  spec/models/micropost_spec.rb
  spec/requests/microposts_request_spec.rb
Labels: deploy

#36 feat: User一覧へのPagination機能追加
  Gemfile
  Gemfile.lock
  app/controllers/users_controller.rb
  app/views/users/index.html.erb
  config/initializers/kaminari_config.rb
Labels: feature

#38 feat:micropostのindexとshowのviewを追加
  app/controllers/microposts_controller.rb
  app/views/microposts/index.html.erb
  app/views/microposts/show.html.erb
Labels: feature
